version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: build/docker/Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ../.env
    environment:
      - APP_PORT=${APP_PORT}
      - ENV=${ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  pgdata:
